### ISSUE TITLE
PyTorch Vesion Demo model file

### ISSUE THREAD

**Issue by AlphaNext** [Khurramjaved96/Dicta#2]
Hello, I want to _run demo.py_, but can't find the PyToch model (*.pb) in PyTorch Branch,  follow the link  [https://drive.google.com/drive/folders/1N9M8dHIMt6sQdoqZ8Y66EJVQSaBTq9cX](url), find _documentModelPyTorch_ and   _cornerModelPyTorch_, so could you tell me how to use it , Thanks

**Comment by kjaved0** [comment]
Hey, 

You just pass the two model files to demo.py using --documentModel and --cornerModel parameters.
