### ISSUE TITLE
IOU

### ISSUE THREAD

**Issue by Vaalizaadeh** [Khurramjaved96/Dicta#3]
I guess there has been something wrong in `intersection_with_correction` function. The following lines:

```
`
    min_x = min(a[0][0], a[1][0], a[2][0], a[3][0])
    min_y = min(a[0][1], a[1][1], a[2][0], a[3][0])
    max_x = max(a[0][0], a[1][0], a[2][0], a[3][0])
    max_y = max(a[0][1], a[1][1], a[2][0], a[3][0])
`
```

should be changed to:

`
```
    min_x = min(a[0][0], a[1][0], a[2][0], a[3][0])
    min_y = min(a[0][1], a[1][1], a[2][1], a[3][1])
    max_x = max(a[0][0], a[1][0], a[2][0], a[3][0])
    max_y = max(a[0][1], a[1][1], a[2][1], a[3][1])
```
`

Also the followning lines: 

`
```
    img1 = cv2.warpPerspective(img1, mat, tuple((img.shape[0], img.shape[1])))
    img2 = cv2.warpPerspective(img2, mat, tuple((img.shape[0], img.shape[1])))
```
`

should be changed to:

`
```
    img1 = cv2.warpPerspective(img1, mat, tuple((img.shape[1], img.shape[0])))
    img2 = cv2.warpPerspective(img2, mat, tuple((img.shape[1], img.shape[0])))
```
`

**Comment by kjaved0** [comment]
You are definitely right about the first case. Thank you for pointing out the issue; I've made the changes. (I've also added the "intersection_with_correction_smart_doc_implementation" function which is the implementation used in the original SmartDoc implementation; only found this implementation recently.)
I'll test the second issue in a few days and make the change if necessary. 

Thanks again for pointing out the problem.
