### ISSUE TITLE
New pre-train models?

### ISSUE THREAD

**Issue by duchengyao** [Khurramjaved96/Dicta#4]
Awesome project!

But after downloading your [pre-train models](https://drive.google.com/drive/folders/1N9M8dHIMt6sQdoqZ8Y66EJVQSaBTq9cX)`documentModelPyTorch` and `cornerModelPyTorch`, there is nothing about FC2 layer about this [commit](https://github.com/Khurramjaved96/Recursive-CNNs/commit/3a055efcca8bc091bdc825f49a1ba9492afa8848#diff-1f7adff4a2a1c2334dd9752ad14d1a50R82).

Could you please upgrade the pre-train models?

Thanks ^_^

**Comment by ziyuwzf** [comment]
> Awesome project!
> 
> But after downloading your [pre-train models](https://drive.google.com/drive/folders/1N9M8dHIMt6sQdoqZ8Y66EJVQSaBTq9cX)`documentModelPyTorch` and `cornerModelPyTorch`, there is nothing about FC2 layer about this [commit](https://github.com/Khurramjaved96/Recursive-CNNs/commit/3a055efcca8bc091bdc825f49a1ba9492afa8848#diff-1f7adff4a2a1c2334dd9752ad14d1a50R82).
> 
> Could you please upgrade the pre-train models?
> 
> Thanks ^_^

hello ,do you solve this problem?my error:
 File "evaluate.py", line 25, in <module>
    corners_extractor = evaluation.corner_extractor.GetCorners("./documentModelPyTorch")
  File "/home/wzf/project/OCR/dewarp/Recursive-CNNs-Pytorch-RecursiveCNN/evaluation/corner_extractor.py", line 16, in __init__
    self.model.load_state_dict(torch.load(checkpoint_dir, map_location='cpu'))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CifarResNet:
	Missing key(s) in state_dict: "fc2.weight", "fc2.bias".

**Comment by peterdk** [comment]
I am also getting this error with the pretrained model. Tensorflow one works great, but wanted to try this one. Will train probably myself, but for a quick evaluation it's very useful to have the pre trained. Also interested in the fully connected networks. Any progress on those?
This project is quite awesome!

```Traceback (most recent call last):
  File "demo.py", line 28, in <module>
    corners_extractor = evaluation.corner_extractor.GetCorners(args.documentModel)
  File "/Users/peter/git/tmp/Recursive-CNNs-pytorch/evaluation/corner_extractor.py", line 16, in __init__
    self.model.load_state_dict(torch.load(checkpoint_dir, map_location='cpu'))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CifarResNet:
	Missing key(s) in state_dict: "fc2.weight", "fc2.bias".```

**Comment by duchengyao** [comment]
I am using older version.

**Comment by hala3** [comment]
can i  extract a document from a video with your code ??

**Comment by harrytruong0804** [comment]
I had the same problem. Missing key(s) in state_dict: "fc2.weight", "fc2.bias". I remove fc2 from the network and run again. The code run successfully and produced the output. However, the result is not good. the detected corners are too far from the groundtruths 
  

![1](https://user-images.githubusercontent.com/16098197/145761347-a1e9a75e-2bec-4f8c-b65d-84d4a0710eb0.jpeg)

**Comment by Janebhop** [comment]
[this solution](https://stackoverflow.com/questions/54058256/runtimeerror-errors-in-loading-state-dict-for-resnet) can solve this problem
