### ISSUE TITLE
.pb pre-trained models 

### ISSUE THREAD

**Issue by ldenoue** [Khurramjaved96/Dicta#7]
The google drive doesn't have the pre-trained Tensorflow models anymore.
Any chance you could add them back there?

**Comment by kjaved0** [comment]
Hey, 
The tensorflow models are in the repository and not google drive. They are in the "TrainedModels" folder (Checkout 'server_branch' to see the folder).

server_branch:
https://github.com/Khurramjaved96/Recursive-CNNs/tree/server_branch

**Comment by ldenoue** [comment]
Sorry about that, thank you!
